package domains


type Banks struct {
	nome string
	code string
}

const (
	BANCO_DO_BRASIL                = Banks{"001", "BANCO DO BRASIL S.A."}
	BCO_DA_AMAZONIA                = Banks{"003", "BANCO DA AMAZONIA S.A."}
	BCO_DO_NORDESTE                = Banks{"004", "BANCO DO NORDESTE DO BRASIL S.A."}
	BNDES                          = Banks{"007", "BNDES"}
	CREDICOAMO                     = Banks{"010", "CREDICOAMO"}
	C_SUISSE_HEDGING               = Banks{"011", "C.SUISSE HEDGING-GRIFFO"}
	BANCO_INBURSA                  = Banks{"012", "BANCO INBURSA"}
	STATE_STREET_BR                = Banks{"014", "STATE STREET BR S.A. BCO COMERCIAL"}
	UBS_BRASIL_CCTVM               = Banks{"015", "UBS BRASIL CCTVM S.A."}
	SICOOB_CREDITRAN               = Banks{"016", "SICOOB CREDITRAN"}
	BNY_MELLON                     = Banks{"017", "BNY MELLON BCO S.A."}
	BCO_TRICURY                    = Banks{"018", "BCO TRICURY S.A."}
	BCO_BANESTES                   = Banks{"021", "BCO BANESTES S.A."}
	BCO_BANDEPE                    = Banks{"024", "BCO BANDEPE S.A."}
	BCO_ALFA                       = Banks{"025", "BCO ALFA S.A."}
	BANCO_ITAÚ_CONSIGNADO          = Banks{"029", "BANCO ITAÚ CONSIGNADO S.A."}
	BANCO_SANTANDER                = Banks{"033", "BANCO SANTANDER (BRASIL) S.A."}
	BCO_BBI                        = Banks{"036", "BCO BBI S.A."}
	BCO_DO_EST_PA                  = Banks{"037", "BCO DO EST. DO PA S.A."}
	BCO_CARGILL                    = Banks{"040", "BCO CARGILL S.A."}
	BCO_DO_ESTADO                  = Banks{"041", "BCO DO EST. DO RS S.A."}
	BCO_DO_EST_SE                  = Banks{"047", "BCO DO EST. DE SE S.A."}
	CONFIDENCE_CC                  = Banks{"060", "CONFIDENCE CC LTDA."}
	HIPERCARD_BM                   = Banks{"062", "HIPERCARD BM S.A."}
	BANCO_BRADESCARD               = Banks{"063", "BANCO BRADESCARD S.A."}
	GOLDMAN_SACHS                  = Banks{"064", "GOLDMAN SACHS DO BRASIL BM S.A."}
	BCO_ANDBANK                    = Banks{"065", "BCO ANDBANK S.A."}
	BCO_MORGAN_STANLEY             = Banks{"066", "BCO MORGAN STANLEY S.A."}
	BCO_CREFISA                    = Banks{"069", "BCO CREFISA S.A."}
	BRBBCO                         = Banks{"070", "BRB - BCO DE BRASILIA S.A."}
	BC__J                          = Banks{"074", "BCO RURAL MAIS S.A."}
	BCO_ABN_AMRO                   = Banks{"075", "BCO ABN AMRO S.A."}
	BCO_KDB_BRASIL                 = Banks{"076", "BCO KDB BRASIL S.A."}
	BANCO_INTER                    = Banks{"077", "BANCO INTER"}
	HAITONG_BI_DO                  = Banks{"078", "HAITONG BI DO BRASIL S.A."}
	BCO_ORIGINAL_DO                = Banks{"079", "BCO ORIGINAL DO AGRONEGOCIO S/A."}
	B_T_CC                         = Banks{"080", "B&T CC LTDA."}
	BANCOSEGURO_S_A                = Banks{"081", "BANCOSEGURO S.A."}
	BANCO_TOPÁZIO_S                = Banks{"082", "BANCO TOPÁZIO S.A."}
	BCO_DA_CHINA                   = Banks{"083", "BCO DA CHINA BRASIL S.A."}
	UNIPRIME_NORTE_DO              = Banks{"084", "UNIPRIME NORTE DO PARANA - CC LTDA."}
	COOP_CENTRAL_AILOS             = Banks{"085", "COOP CENTRAL AILOS"}
	CREDISAN_CC                    = Banks{"089", "CREDISAN CC"}
	CCCM_UNICRED_CENTRAL           = Banks{"091", "CCCM UNICRED CENTRAL RS"}
	BRK_S_A                        = Banks{"092", "BRK S.A. CFI"}
	POLOCRED_SCMEPP_LTDA           = Banks{"093", "POLOCRED SCMEPP LTDA"}
	BANCO_FINAXIS                  = Banks{"094", "BANCO FINAXIS"}
	TRAVELEX_BANCO                 = Banks{"095", "TRAVELEX BANCO DE CÂMBIO S.A."}
	BCO_B3_S                       = Banks{"096", "BCO B3 S.A."}
	CREDISIS_CENTRAL               = Banks{"097", "CREDISIS CENTRAL DE COOPERATIVAS DE CRÉDITO LTDA"}
	CREDIALIANÇA_CCR               = Banks{"098", "CREDIALIANÇA CCR LTDA."}
	UNIPRIME_CENTRAL_CCC           = Banks{"099", "UNIPRIME CENTRAL CCC LTDA."}
	PLANNER_CV_S                   = Banks{"100", "PLANNER CV S.A. CFI"}
	RENASCENCA_DTVM_LTDA           = Banks{"101", "RENASCENCA DTVM LTDA."}
	XP_INVESTIMENTOS_CCTVM         = Banks{"102", "XP INVESTIMENTOS CCTVM S.A."}
	CAIXA_ECONÔMICA_FEDERAL        = Banks{"104", "CAIXA ECONÔMICA FEDERAL"}
	LECCA_CFI_S                    = Banks{"105", "LECCA CFI S.A."}
	BCO_BOCOM_BBM                  = Banks{"107", "BCO BOCOM BBM S.A."}
	PORTOCRED_S_A                  = Banks{"108", "PORTOCRED S.A."}
	OLIVEIRA_TRUST_DTVM            = Banks{"111", "OLIVEIRA TRUST DTVM S.A."}
	MAGLIANO_S_A                   = Banks{"113", "MAGLIANO S.A. CCVM"}
	CENTRAL_COOPERATIVA_DE         = Banks{"114", "CENTRAL COOPERATIVA DE CRÉDITO NO ESTADO DO ESPIRITO SANTO"}
	ADVANCED_CC_LTDA               = Banks{"117", "ADVANCED CC LTDA."}
	BCO_WESTERN_UNION              = Banks{"119", "BCO WESTERN UNION"}
	BCO_RODOBENS_S                 = Banks{"120", "BCO RODOBENS S.A."}
	BCO_AGIBANK_S                  = Banks{"121", "BCO AGIBANK S.A."}
	BCO_BRADESCO_BERJ              = Banks{"122", "BCO BRADESCO BERJ S.A."}
	BCO_WOORI_BANK                 = Banks{"124", "BCO WOORI BANK DO BRASIL S.A."}
	PLURAL_BCO_BM                  = Banks{"125", "PLURAL BCO BM "}
	BR_PARTNERS_BI                 = Banks{"126", "BR PARTNERS BI S.A."}
	CODEPE_CVC_S                   = Banks{"127", "CODEPE CVC S.A."}
	MS_BANK_S                      = Banks{"128", "MS BANK S.A. BCO DE CÂMBIO"}
	UBS_BRASIL_BI                  = Banks{"129", "UBS BRASIL BI S.A."}
	CARUANA_SCFI                   = Banks{"130", "CARUANA S.A. CFI"}
	TULLETT_PREBON_BRASIL          = Banks{"131", "TULLETT PREBON BRASIL CVC LTDA."}
	ICBC_DO_BRASIL                 = Banks{"132", "ICBC DO BRASIL BM S.A."}
	CRESOL_CONFEDERAÇÃO            = Banks{"133", "CRESOL CONFEDERAÇÃO"}
	BGC_LIQUIDEZ_DTVM              = Banks{"134", "BGC LIQUIDEZ DTVM LTDA."}
	UNICRED                        = Banks{"136", "UNICRED CENTRAL DO RIO GRANDE DO SUL"}
	GET_MONEY_CC                   = Banks{"138", "GET MONEY CC LTDA."}
	INTESA_SANPAOLO_BRASIL         = Banks{"139", "INTESA SANPAOLO BRASIL S.A. BM"}
	EASYNVEST_TÍTULO               = Banks{"140", "EASYNVEST - TÍTULO CV S.A."}
	BROKER_BRASIL_CC               = Banks{"142", "BROKER BRASIL CC LTDA."}
	TREVISO_CC_S                   = Banks{"143", "TREVISO CC S.A."}
	BEXS_BCO_DE                    = Banks{"144", "BEXS BCO DE CÂMBIO S.A."}
	LEVYCAM_CCV_LTDA               = Banks{"145", "LEVYCAM CCV LTDA."}
	GUITTA_CC_LTDA                 = Banks{"146", "GUITTA CC LTDA."}
	FACTA_S_A                      = Banks{"149", "FACTA S.A. CFI"}
	ICAP_DO_BRASIL                 = Banks{"157", "ICAP DO BRASIL DTVM LTDA."}
	CASA_CREDITO_S                 = Banks{"159", "CASA CREDITO S.A. SCM"}
	COMMERZBANK_BRASIL_S           = Banks{"163", "COMMERZBANK BRASIL S.A. - BCO MÚLTIPLO"}
	BCO_OLÉ_BONSUCESSO             = Banks{"169", "BCO OLÉ BONSUCESSO CONSIGNADO S.A."}
	BRL_TRUST_DTVM                 = Banks{"173", "BRL TRUST DTVM S.A."}
	PERNAMBUCANAS_FINANC_S         = Banks{"174", "PERNAMBUCANAS FINANC S.A. BM"}
	GUIDE                          = Banks{"177", "GUIDE"}
	CM_CAPITAL_MARKETS             = Banks{"180", "CM CAPITAL MARKETS CCTVM LTDA."}
	SOCRED_SA                      = Banks{"183", "SOCRED S.A."}
	BCO_ITAÚ_BBA                   = Banks{"184", "BCO ITAÚ BBA S.A."}
	ATIVA_S_A                      = Banks{"188", "ATIVA S.A. INVESTIMENTOS CCTVM"}
	HS_FINANCEIRA                  = Banks{"189", "HS FINANCEIRA"}
	SERVICOOP                      = Banks{"190", "SERVICOOP"}
	NOVA_FUTURA_CTVM               = Banks{"191", "NOVA FUTURA CTVM LTDA."}
	PARMETAL_DTVM_LTDA             = Banks{"194", "PARMETAL DTVM LTDA."}
	FAIR_CC_S                      = Banks{"196", "FAIR CC S.A."}
	STONE_PAGAMENTOS_S             = Banks{"197", "STONE PAGAMENTOS S.A."}
	BANCO_BTG_PACTUAL              = Banks{"208", "BANCO BTG PACTUAL S.A."}
	BANCO_ORIGINAL                 = Banks{"212", "BANCO ORIGINAL"}
	BCO_ARBI_S                     = Banks{"213", "BCO ARBI S.A."}
	BANCO_JOHN_DEERE               = Banks{"217", "BANCO JOHN DEERE S.A."}
	BCO_BS2_S                      = Banks{"218", "BCO BS2 S.A."}
	BCO_CRÉDIT_AGRICOLE            = Banks{"222", "BCO CRÉDIT AGRICOLE BR S.A."}
	BCO_FIBRA_S                    = Banks{"224", "BCO FIBRA S.A."}
	BANCO_CIFRA                    = Banks{"233", "BANCO CIFRA S.A."}
	BANCO_BRADESCO_S               = Banks{"237", "BANCO BRADESCO S.A."}
	BCO_CLASSICO_S                 = Banks{"241", "BCO CLASSICO S.A."}
	BCO_MÁXIMA_S                   = Banks{"243", "BCO MÁXIMA S.A."}
	BCO_ABC_BRASIL                 = Banks{"246", "BCO ABC BRASIL S.A."}
	BANCO_INVESTCRED_UNIBANCO      = Banks{"249", "BANCO INVESTCRED UNIBANCO S.A."}
	BCV                            = Banks{"250", "BCV"}
	BEXS_CC_S                      = Banks{"253", "BEXS CC S.A."}
	PARANA_BCO_S                   = Banks{"254", "PARANA BCO S.A."}
	MONEYCORP_BCO_DE               = Banks{"259", "MONEYCORP BCO DE CÂMBIO S.A."}
	NU_PAGAMENTOS_S                = Banks{"260", "NU PAGAMENTOS S.A."}
	BCO_FATOR_S                    = Banks{"265", "BCO FATOR S.A."}
	BCO_CEDULA_S                   = Banks{"266", "BCO CEDULA S.A."}
	BARI_CIA_HIPOTECÁRIA           = Banks{"268", "BARI CIA HIPOTECÁRIA"}
	HSBC_BANCO_DE                  = Banks{"269", "HSBC BANCO DE INVESTIMENTO"}
	SAGITUR_CC_LTDA                = Banks{"270", "SAGITUR CC LTDA."}
	IB_CCTVM_S                     = Banks{"271", "IB CCTVM S.A."}
	AGK_CC_S                       = Banks{"272", "AGK CC S.A."}
	CCR_DE_SÃO                     = Banks{"273", "CCR DE SÃO MIGUEL DO OESTE"}
	MONEY_PLUS_SCMEPP              = Banks{"274", "MONEY PLUS SCMEPP LTDA."}
	SENFF_S_A                      = Banks{"276", "SENFF S.A. - CFI."}
	GENIAL_INVESTIMENTOS_CVM       = Banks{"278", "GENIAL INVESTIMENTOS CVM S.A."}
	CCR_DE_PRIMAVERA               = Banks{"279", "CCR DE PRIMAVERA DO LESTE"}
	AVISTA_S_A                     = Banks{"280", "AVISTA S.A. CFI"}
	CCR_COOPAVEL                   = Banks{"281", "CCR COOPAVEL"}
	RB_CAPITAL_INVESTIMENTOS       = Banks{"283", "RB CAPITAL INVESTIMENTOS DTVM LTDA."}
	FRENTE_CC_LTDA                 = Banks{"285", "FRENTE CC LTDA."}
	CCR_DE_OURO                    = Banks{"286", "CCR DE OURO PRETO"}
	CAROL_DTVM_LTDA                = Banks{"288", "CAROL DTVM LTDA."}
	DECYSEO_CC_LTDA                = Banks{"289", "DECYSEO CC LTDA."}
	PAGSEGURO                      = Banks{"290", "PAGSEGURO"}
	BS2_DTVM_S                     = Banks{"292", "BS2 DTVM S.A."}
	LASTRO_RDV_DTVM                = Banks{"293", "LASTRO RDV DTVM LTDA."}
	VISION_S_A                     = Banks{"296", "VISION S.A. CFI"}
	VIPS_CC_LTDA                   = Banks{"298", "VIPS CC LTDA."}
	SOROCRED_CFI_S                 = Banks{"299", "SOROCRED CFI S.A."}
	BCO_LA_NACION                  = Banks{"300", "BCO LA NACION ARGENTINA"}
	BPP_IP_S                       = Banks{"301", "BPP IP S.A."}
	PORTOPAR_DTVM_LTDA             = Banks{"306", "PORTOPAR DTVM LTDA."}
	TERRA_INVESTIMENTOS_DTVM       = Banks{"307", "TERRA INVESTIMENTOS DTVM"}
	CAMBIONET_CC_LTDA              = Banks{"309", "CAMBIONET CC LTDA."}
	VORTX_DTVM_LTDA                = Banks{"310", "VORTX DTVM LTDA."}
	PI_DTVM_S                      = Banks{"315", "PI DTVM S.A."}
	BCO_BMG_S                      = Banks{"318", "BCO BMG S.A."}
	OM_DTVM_LTDA                   = Banks{"319", "OM DTVM LTDA."}
	BCO_CCB_BRASIL                 = Banks{"320", "BCO CCB BRASIL S.A."}
	CREFAZ_SCMEPP_LTDA             = Banks{"321", "CREFAZ SCMEPP LTDA."}
	CCR_DE_ABELARDO                = Banks{"322", "CCR DE ABELARDO LUZ"}
	MERCADO_PAGO                   = Banks{"323", "MERCADO PAGO"}
	ÓRAMA_DTVM_S                   = Banks{"325", "ÓRAMA DTVM S.A."}
	PARATI_CFI                     = Banks{"326", "PARATI CFI S.A."}
	QI_SCD_S                       = Banks{"329", "QI SCD S.A."}
	BANCO_BARI_S                   = Banks{"330", "BANCO BARI S.A."}
	FRAM_CAPITAL_DTVM              = Banks{"331", "FRAM CAPITAL DTVM S.A."}
	ACESSO                         = Banks{"332", "ACESSO"}
	BANCO_DIGIO                    = Banks{"335", "BANCO DIGIO"}
	BCO_C6_S                       = Banks{"336", "BCO C6 S.A."}
	SUPER_PAGAMENTOS_E             = Banks{"340", "SUPER PAGAMENTOS E ADMINISTRAÇÃO DE MEIOS ELETRÔNICOS S.A."}
	ITAÚ_UNIBANCO_S                = Banks{"341", "ITAÚ UNIBANCO S.A."}
	CREDITAS_SCD                   = Banks{"342", "CREDITAS SCD S.A."}
	FFA_SCMEPP_LTDA                = Banks{"343", "FFA SCMEPP LTDA."}
	BCO_XP_S                       = Banks{"348", "BCO XP S.A."}
	AMAGGI_S_A                     = Banks{"349", "AMAGGI S.A. CFI"}
	TORO_CTVM_LTDA                 = Banks{"352", "TORO CTVM LTDA."}
	NECTON_INVESTIMENTOS_S         = Banks{"354", "NECTON INVESTIMENTOS S.A."}
	ÓTIMO_SCD_S                    = Banks{"355", "ÓTIMO SCD S.A."}
	GERENCIANET_PAGTOS_BRASIL      = Banks{"364", "GERENCIANET PAGTOS BRASIL S.A."}
	SOLIDUS_S_A                    = Banks{"365", "SOLIDUS S.A. CFI"}
	BCO_SOCIETE_GENERALE           = Banks{"366", "BCO SOCIETE GENERALE BRASIL S.A."}
	VITREO_DTVM_S                  = Banks{"367", "VITREO DTVM S.A."}
	BCO_MIZUHO_S                   = Banks{"370", "BCO MIZUHO S.A."}
	UP_P_SEP                       = Banks{"373", "UP.P SEP S.A."}
	BCO_J_P                        = Banks{"376", "BCO J.P. MORGAN S.A."}
	BCO_MERCANTIL_DO               = Banks{"389", "BCO MERCANTIL DO BRASIL S.A."}
	BCO_BRADESCO_FINANC            = Banks{"394", "BCO BRADESCO FINANC S.A."}
	KIRTON_BANK                    = Banks{"399", "KIRTON BANK"}
	BCO_CAPITAL_S                  = Banks{"412", "BCO CAPITAL S.A."}
	BCO_BV_S                       = Banks{"413", "BCO BV S.A."}
	BCO_SAFRA_S                    = Banks{"422", "BCO SAFRA S.A."}
	FITBANK_PAGAMENTOS_ELETRONICOS = Banks{"450", "FITBANK PAGAMENTOS ELETRÔNICOS S.A."}
	BCO_MUFG_BRASIL                = Banks{"456", "BCO MUFG BRASIL S.A."}
	BCO_SUMITOMO_MITSUI            = Banks{"464", "BCO SUMITOMO MITSUI BRASIL S.A."}
	BCO_CAIXA_GERAL                = Banks{"473", "BCO CAIXA GERAL BRASIL S.A."}
	CITIBANK_N_A                   = Banks{"477", "CITIBANK N.A."}
	BCO_ITAUBANK_S                 = Banks{"479", "ITAUBANK S.A."}
	DEUTSCHE_BANK_S                = Banks{"487", "DEUTSCHE BANK S.A. BCO ALEMAO"}
	JPMORGAN_CHASE_BANK            = Banks{"488", "JPMORGAN CHASE BANK"}
	ING_BANK_N                     = Banks{"492", "ING BANK N.V."}
	BCO_LA_PROVINCIA               = Banks{"495", "BCO LA PROVINCIA B AIRES BCE"}
	BCO_CREDIT_SUISSE              = Banks{"505", "BCO CREDIT SUISSE S.A."}
	SENSO_CCVM_S                   = Banks{"545", "SENSO CCVM S.A."}
	BCO_LUSO_BRASILEIRO            = Banks{"600", "BCO LUSO BRASILEIRO S.A."}
	BCO_INDUSTRIAL_DO              = Banks{"604", "BCO INDUSTRIAL DO BRASIL S.A."}
	BCO_VR_S                       = Banks{"610", "BCO VR S.A."}
	BCO_PAULISTA_S                 = Banks{"611", "BCO PAULISTA S.A."}
	BCO_GUANABARA_S                = Banks{"612", "BCO GUANABARA S.A."}
	OMNI_BANCO_S                   = Banks{"613", "OMNI BANCO S.A."}
	BANCO_PAN                      = Banks{"623", "BANCO PAN"}
	BCO_FICSA_S                    = Banks{"626", "BCO FICSA S.A."}
	SMARTBANK                      = Banks{"630", "SMARTBANK"}
	BCO_RENDIMENTO_S               = Banks{"633", "BCO RENDIMENTO"}
	BCO_TRIANGULO_S                = Banks{"634", "BCO TRIANGULO S.A."}
	BCO_SOFISA_S                   = Banks{"637", "BCO SOFISA S.A."}
	BCO_PINE_S                     = Banks{"643", "BCO PINE S.A."}
	ITAÚ_UNIBANCO_HOLDING          = Banks{"652", "ITAÚ UNIBANCO HOLDING S.A."}
	BCO_INDUSVAL_S                 = Banks{"653", "BCO INDUSVAL S.A."}
	BCO_A_J                        = Banks{"654", "BCO A.J. RENNER S.A."}
	BCO_DAYCOVAL_S                 = Banks{"707", "BCO DAYCOVAL S.A."}
	BCO_OURINVEST_S                = Banks{"712", "BCO OURINVEST S.A."}
	BANCO_NEON                     = Banks{"735", "BANCO NEON"}
	BCO_CETELEM_S                  = Banks{"739", "BCO CETELEM S.A."}
	BCO_RIBEIRAO_PRETO             = Banks{"741", "BCO RIBEIRAO PRETO S.A."}
	BANCO_SEMEAR                   = Banks{"743", "BANCO SEMEAR"}
	BCO_CITIBANK_S                 = Banks{"745", "BCO CITIBANK S.A."}
	BCO_MODAL_S                    = Banks{"746", "BCO MODAL S.A."}
	BCO_RABOBANK_INTL              = Banks{"747", "BCO RABOBANK INTL BRASIL S.A."}
	BCO_COOPERATIVO_SICREDI        = Banks{"748", "BCO COOPERATIVO SICREDI S.A."}
	SCOTIABANK_BRASIL              = Banks{"751", "SCOTIABANK BRASIL"}
	BCO_BNP_PARIBAS                = Banks{"752", "BCO BNP PARIBAS BRASIL S.A."}
	NOVO_BCO_CONTINENTAL           = Banks{"753", "NOVO BCO CONTINENTAL S.A. - BM"}
	BANCO_SISTEMA                  = Banks{"754", "BANCO SISTEMA"}
	BOFA_MERRILL_LYNCH             = Banks{"755", "BOFA MERRILL LYNCH BM S.A."}
	BANCOOB                        = Banks{"756", "BANCOOB"}
	BCO_KEB_HANA                   = Banks{"757", "BCO KEB HANA DO BRASIL S.A."}
	CLARO_PAY_S                    = Banks{"759", "CLARO PAY S.A."}
)