package domains

type Profession struct {
	profession string
}

var (
	ACOUGUEIRO                                    Profession = Profession{"Acougueiro"}
	ACUMPURISTA                                   Profession = Profession{"Acumpurista"}
	ADESTRADOR                                    Profession = Profession{"Adestrador/Tratador de Animais/Treinador de Animais"}
	ADMINISTRADOR                                 Profession = Profession{"Administrador"}
	ADVOGADO                                      Profession = Profession{"Advogado"}
	AEROVIARIO                                    Profession = Profession{"Aeroviario/Empregado de Aeroporto"}
	AFIADOR                                       Profession = Profession{"Afiador"}
	AGENCIADOR_DE_PROPAGANDA                      Profession = Profession{"Agenciador de Propaganda"}
	AGENCIADOR_CARGAS_TRANSPORTES                 Profession = Profession{"Agenciador de Serv. Cargas/Transportes"}
	AGENTE_ADMINISTRATIVO                         Profession = Profession{"Agente Administrativo"}
	AGENTE_DE_COMPRA_VENDA                        Profession = Profession{"Agente de Compra e Venda"}
	AGENTE_DE_SERVICOS_FUNERARIOS                 Profession = Profession{"Agente de Serviços Funerarios"}
	AGENTE_DE_VIAGEM                              Profession = Profession{"Agente de viagem/Agente de turismo/Operador de turismo"}
	AGRONOMO                                      Profession = Profession{"Agronomo"}
	AJUDANTE_GERAL                                Profession = Profession{"Ajudante Geral"}
	AJUSTADOR_RETIFICADOR                         Profession = Profession{"Ajustador/Retificador"}
	ALFAIATE                                      Profession = Profession{"Alfaiate"}
	AMBULANTES                                    Profession = Profession{"Ambulantes{Camelo,Pipoqueiro,etc}"}
	ANALISTA_RECURSOS_HUMANOS                     Profession = Profession{"Analista de Cargos/Recursos Humanos etc"}
	ANALISTA_CREDITO_E_COBRANCA                   Profession = Profession{"Analista de Cred/Cad/Cobr/Garant/Inf etc"}
	ANALISTA_CUSTOS_PROJ_SERV_ECONOMIA            Profession = Profession{"Analista de Custos/Proj/Serv/Economia etc"}
	ANALISTA_PRODUCAO_CRONOALISTA                 Profession = Profession{"Analista de Producao/Cronoalista"}
	ANALISTA_SISTEMAS                             Profession = Profession{"Analista de Sistemas"}
	APOSENTADO_                                   Profession = Profession{"Aposentado exceto funcionario publico"}
	ARBITRO_DE_ESPORTES                           Profession = Profession{"Arbitro de Esportes"}
	ARMADOR_DE_FERRAGENS                          Profession = Profession{"Armador de Ferragens"}
	ARMEIRO                                       Profession = Profession{"Armeiro"}
	ARQUEOLOGO                                    Profession = Profession{"Arqueologo"}
	ARQUITETO                                     Profession = Profession{"Arquiteto"}
	ARQUIVISTA                                    Profession = Profession{"Arquivista"}
	ARTESAO                                       Profession = Profession{"Artesao"}
	ARTISTA_PLASTICO                              Profession = Profession{"Artista Plastico"}
	ASCENSORISTA                                  Profession = Profession{"Ascensorista"}
	ASSISTENTE_SOCIAL                             Profession = Profession{"Assistente Social"}
	ASTRONOMO                                     Profession = Profession{"Astronomo"}
	ATLETA                                        Profession = Profession{"Atleta Profissional"}
	ATOR                                          Profession = Profession{"Ator"}
	ATUARIO                                       Profession = Profession{"Atuario"}
	AUDITOR_PUBLICO                               Profession = Profession{"Auditor Publico"}
	AUXILIAR_COZINHA_LIMPEZA_COSTURA_COPA         Profession = Profession{"Auxiliar Cozinha/Limpeza/Costura/Copa etc"}
	AUXILIAR_DE_ENFERMAGEM_TECNICO                Profession = Profession{"Auxiliar de Enfermagem/Tecnico de Enfermagem"}
	AUXILIAR_DE_ESCRITORIO                        Profession = Profession{"Auxiliar de Escritorio e Ass."}
	AUXILIAR_DE_LABORATORIO                       Profession = Profession{"Auxiliar de Laboratorio"}
	AUXILIAR_DE_SERVICOS_GERAIS                   Profession = Profession{"Auxiliar de Serviços Gerais"}
	AVALIADOR                                     Profession = Profession{"Avaliador"}
	CUIDADOR                                      Profession = Profession{"Cuidador"}
	DANCARINO                                     Profession = Profession{"Dançarino"}
	BANCARIO                                      Profession = Profession{"Bancario"}
	BARBEIRO                                      Profession = Profession{"Barbeiro"}
	BARISTA                                       Profession = Profession{"Barista/Barman/Barwoman"}
	BIBLIOTECARIO                                 Profession = Profession{"Bibliotecario"}
	BILHETEIRO_COBRADOR                           Profession = Profession{"Bilheteiro{Transp/Diversao}/Trocador/Cobrador Transp Passageiro/Caixa"}
	BIOLOGO                                       Profession = Profession{"Biologo"}
	BIOMEDICO                                     Profession = Profession{"Biomedico"}
	BOLSISTA                                      Profession = Profession{"Bolsista"}
	BOMBEIRO_ENCANADOR                            Profession = Profession{"Bombeiro/Encanador"}
	BORRACHEIRO                                   Profession = Profession{"Borracheiro"}
	CABELEIREIRO                                  Profession = Profession{"Cabeleireiro"}
	CAIXEIRO_VIAJANTE                             Profession = Profession{"Caixeiro-Viajante"}
	CAMAREIRA_ARRUMADEIRA                         Profession = Profession{"Camareira/Arrumadeira"}
	CANTOR                                        Profession = Profession{"Cantor"}
	CARGOS_DE_CONFIANCA_COMISSOES                 Profession = Profession{"Cargos de Confiança/Comissoes"}
	CARREGADOR                                    Profession = Profession{"Carregador"}
	CARTEIRO                                      Profession = Profession{"Carteiro"}
	CARTORARIO                                    Profession = Profession{"Cartorario"}
	CASEIRO                                       Profession = Profession{"Caseiro"}
	CAVALARICO                                    Profession = Profession{"Cavalarico/Ferrador/Tratador de Animais"}
	CENOGRAFO                                     Profession = Profession{"Cenografo"}
	CHAVEIRO                                      Profession = Profession{"Chaveiro"}
	CHEFE_DA_PRODUCAO                             Profession = Profession{"Chefe da Producao"}
	CHEFE_INTERMEDIARIO                           Profession = Profession{"Chefe Intermediario"}
	COBRADOR_EM_GERAL                             Profession = Profession{"Cobrador em Geral"}
	COMANDANTE_DE_EMBARCACOES                     Profession = Profession{"Comandante de Embarcacoes"}
	COMENTARISTA                                  Profession = Profession{"Comentarista"}
	COMISSARIO_DE_BORDO                           Profession = Profession{"Comissario de Bordo"}
	COMPOSITOR                                    Profession = Profession{"Compositor"}
	COMUNICOLOGO                                  Profession = Profession{"Comunicologo"}
	CONSELHEIRO_TUTELAR                           Profession = Profession{"Conselheiro Tutelar"}
	CONSULTOR_DE_EMPRESAS                         Profession = Profession{"Consultor de Empresas"}
	CONTADOR                                      Profession = Profession{"Contador"}
	CONTRAMESTRE                                  Profession = Profession{"Contramestre"}
	CONTROLADOR_DE_VOO                            Profession = Profession{"Controlador de Voo"}
	COREOGRAFO                                    Profession = Profession{"Coreografo"}
	CORRETOR_EM_GERAL                             Profession = Profession{"Corretor em Geral"}
	CORTADOR                                      Profession = Profession{"Cortador"}
	COSTUREIRA                                    Profession = Profession{"Costureira/Bordadeira/Cerzideira"}
	COZINHEIRO_CONFEITEIRO_PADEIRO                Profession = Profession{"Cozinheiro/Confeiteiro/Padeiro"}
	DECORADOR                                     Profession = Profession{"Decorador"}
	DEGUSTADOR_VINHO_CAFE                         Profession = Profession{"Degustador{Vinho/Café etc}"}
	DELEGADO_DE_POLICIA                           Profession = Profession{"Delegado de Policia"}
	DEMONSTRADOR                                  Profession = Profession{"Demonstrador"}
	DENTISTA_ODONTOLOGO                           Profession = Profession{"Dentista/Odontologo"}
	DEPILADOR                                     Profession = Profession{"Depilador"}
	DEPUTADO_ESTADUAL_FEDERAL                     Profession = Profession{"Deputado Estadual/Federal"}
	DESEMBARGADOR                                 Profession = Profession{"Desembargador"}
	DESENHISTA                                    Profession = Profession{"Desenhista"}
	DESPACHANTE_INCLUSIVE_ADUANEIRO               Profession = Profession{"Despachante inclusive aduaneiro"}
	DETETIVE_INVESTIGADOR                         Profession = Profession{"Detetive/Investigador"}
	DETETIZADOR                                   Profession = Profession{"Detetizador"}
	DIGITADOR                                     Profession = Profession{"Digitador"}
	DIPLOMATA                                     Profession = Profession{"Diplomata"}
	DIRETOR_DE_EMPRESA                            Profession = Profession{"Diretor de Empresa"}
	DIRETOR_DE_ESPETACULOS                        Profession = Profession{"Diretor de Espetaculos"}
	DIRETOR_DE_ESTABELECIMENTO_DE_ENSINO          Profession = Profession{"Diretor de Estabelecimento de Ensino"}
	ECONOMISTA                                    Profession = Profession{"Economista"}
	ELETRICISTA                                   Profession = Profession{"Eletricista"}
	EMBALADOR                                     Profession = Profession{"Embalador"}
	EMBALSAMADOR                                  Profession = Profession{"Embalsamador"}
	EMPREGADA_DOMESTICA                           Profession = Profession{"Empregada domestica"}
	EMPRESARIO_DE_ATLETA                          Profession = Profession{"Empresario de Atleta"}
	ENFERMEIRO                                    Profession = Profession{"Enfermeiro"}
	ENGENHEIRO                                    Profession = Profession{"Engenheiro"}
	ENTREVISTADOR_CENSO_PESQUISA_PRECOS           Profession = Profession{"Entrevistador Censo/Pesquisa/Preços"}
	ESCRITOR                                      Profession = Profession{"Escritor"}
	ESCULTOR                                      Profession = Profession{"Escultor"}
	ESOTERICOS_ASTROLOGOS_TAROLOGO_NUMEROLOGO     Profession = Profession{"Esotericos Astrologos/Tarologo/Numerologo etc"}
	ESTATISTICO                                   Profession = Profession{"Estatistico"}
	ESTETICISTA                                   Profession = Profession{"Esteticista"}
	ESTILISTA_MODELISTA                           Profession = Profession{"Estilista/Modelista"}
	ESTIVADOR                                     Profession = Profession{"Estivador"}
	FARMACEUTICO                                  Profession = Profession{"Farmaceutico"}
	FAXINEIRO_DIARISTA                            Profession = Profession{"Faxineiro/Diarista"}
	FEIRANTE                                      Profession = Profession{"Feirante"}
	FERRAMENTEIRO                                 Profession = Profession{"Ferramenteiro"}
	FISCAL                                        Profession = Profession{"Fiscal"}
	FISCAL_DE_PRODUCAO                            Profession = Profession{"Fiscal de Producao"}
	FISCAL_SERVICOS_DE_TRANSPORTE                 Profession = Profession{"Fiscal Serviços de Transporte"}
	FISICO                                        Profession = Profession{"Fisico"}
	FISIOTERAPEUTA                                Profession = Profession{"Fisioterapeuta"}
	FOGUISTA_DE_EMBARCACOES_OU_LOCOMOTIVAS        Profession = Profession{"Foguista de Embarcacoes ou Locomotivas"}
	FONOAUDIOLOGO                                 Profession = Profession{"Fonoaudiologo"}
	FORCAS_ARMADAS_SOLDADO_MARINHEIRO             Profession = Profession{"Forças Armadas Soldado,Marinheiro,etc"}
	FOTOGRAFO                                     Profession = Profession{"Fotografo"}
	FRENTISTA_TRABALHADOR_DE_POSTO_DE_GASOLINA    Profession = Profession{"Frentista/Trabalhador de posto de gasolina"}
	FUNCIONARIO_PUBLICO_CIVIL_APOSENTADO          Profession = Profession{"Funcionario Publico Civil Aposentado"}
	FUNDIDOR                                      Profession = Profession{"Fundidor"}
	GARAGISTA                                     Profession = Profession{"Garagista"}
	GARCOM_MAITRE                                 Profession = Profession{"Garçom/Maitre"}
	GARIMPEIRO                                    Profession = Profession{"Garimpeiro"}
	GEOGRAFO                                      Profession = Profession{"Geografo"}
	GEOLOGO                                       Profession = Profession{"Geologo"}
	GERENTE                                       Profession = Profession{"Gerente"}
	GESSISTA                                      Profession = Profession{"Gessista"}
	GOVERNADOR_DE_ESTADO                          Profession = Profession{"Governador de Estado"}
	GOVERNANTA                                    Profession = Profession{"Governanta"}
	GUIA_TURISTICO                                Profession = Profession{"Guia Turistico"}
	HOSPITAL_TRABALHADORES_EM_GERAL               Profession = Profession{"Hospital - Trabalhadores em Geral"}
	IMPERMEABILIZADOR                             Profession = Profession{"Impermeabilizador"}
	INSPETOR                                      Profession = Profession{"Inspetor"}
	INSPETOR_DE_CONTROLE_DE_QUALIDADE             Profession = Profession{"Inspetor de Controle de Qualidade"}
	INSTALADOR_DE_GAS_AGUA_ESGOTO                 Profession = Profession{"Instalador de Gas,Agua e Esgoto"}
	INSTRUMENTADOR_CIRURGICO                      Profession = Profession{"Instrumentador Cirurgico"}
	INSTRUMENTISTA                                Profession = Profession{"Instrumentista"}
	INSTRUTOR_DE_AUTOESCOLA                       Profession = Profession{"Instrutor de Autoescola"}
	INSTRUTOR_PROFESSOR_CURSOS_LIVRES             Profession = Profession{"Instrutor/Professor de Cursos Livres Ginastica,Ingles,Informatica"}
	INTERPRETE_TRADUTOR                           Profession = Profession{"Interprete/Tradutor"}
	JARDINEIRO                                    Profession = Profession{"Jardineiro"}
	JOALHEIRO                                     Profession = Profession{"Joalheiro"}
	JORNALEIRO                                    Profession = Profession{"Jornaleiro"}
	JORNALISTA_REPORTER                           Profession = Profession{"Jornalista/Reporter"}
	JUIZ_DE_DIREITO                               Profession = Profession{"Juiz de Direito"}
	LANTERNEIRO                                   Profession = Profession{"Lanterneiro"}
	LAVADOR_DE_CARROS_ROUPAS                      Profession = Profession{"Lavador de Carros/Roupas"}
	LEILOEIRO                                     Profession = Profession{"Leiloeiro"}
	LEITURISTA                                    Profession = Profession{"Leiturista"}
	GARI                                          Profession = Profession{"Lixeiro/Gari/Varredor/Coletor de Lixo"}
	LOCUTOR                                       Profession = Profession{"Locutor"}
	MANICURE_PEDICURE_PODOLOGO                    Profession = Profession{"Manicure/Pedicure/Podologo"}
	MANOBRISTA_NAO_EMPREGADO_GUARDADOR_DE_CARRO   Profession = Profession{"Manobrista não empregado}/Guardador de Carro"}
	MAQUILADOR                                    Profession = Profession{"Maquilador"}
	MAQUINISTA_DE_EMBARCACOES_OU_LOCOMOTIVAS      Profession = Profession{"Maquinista de Embarcacoes ou Locomotivas"}
	MARCENEIRO_CARPINTEIRO                        Profession = Profession{"Marceneiro/Carpinteiro"}
	MARINHEIRO_ASS                                Profession = Profession{"Marinheiro e Ass."}
	MASSAGISTA                                    Profession = Profession{"Massagista"}
	MATEMATICO                                    Profession = Profession{"Matematico"}
	MECANICO                                      Profession = Profession{"Mecanico"}
	MEDICO                                        Profession = Profession{"Medico"}
	MEMBRO_DA_DEFENSORIA_PUBLICA                  Profession = Profession{"Membro da Defensoria Publica"}
	MEMBRO_DE_EQUIPE_TECNICA_DE_ESPORTES          Profession = Profession{"Membro de Equipe tecnica de esportes"}
	MEMBRO_DO_MINISTERIO_PUBLICO                  Profession = Profession{"Membro do Ministerio Publico"}
	MEMBRO_EQUIPE_TECNICA_ESPORTES                Profession = Profession{"Membro Equipe Técnica Esportes"}
	MESTRE_DE_PRODUCAO                            Profession = Profession{"Mestre de Producao"}
	METEOROLOGISTA                                Profession = Profession{"Meteorologista"}
	MILITAR_EM_GERAL                              Profession = Profession{"Militar em Geral"}
	MILITAR_REFORMADO                             Profession = Profession{"Militar reformado"}
	MINISTRO_DE_ESTADO                            Profession = Profession{"Ministro de Estado"}
	MINISTRO_DE_TRIBUNAL_SUPERIOR                 Profession = Profession{"Ministro de Tribunal Superior"}
	MODELO_DE_MODAS                               Profession = Profession{"Modelo de Modas"}
	MONTADOR                                      Profession = Profession{"Montador"}
	MOTORISTA_TRANSPORTE_CARGAS                   Profession = Profession{"Motorista veiculo transporte cargas"}
	MOTORISTA_TRANSPORTE_DE_PASSAGEIROS           Profession = Profession{"Motorista veiculo transporte de passageiros"}
	MOTORISTA_AUTONOMO_TAXISTA_PRINCIPAL          Profession = Profession{"Motorista autonomo taxista principal"}
	MUSEOLOGO                                     Profession = Profession{"Museologo"}
	MUSICO                                        Profession = Profession{"Musico"}
	NUTRICIONISTA                                 Profession = Profession{"Nutricionista"}
	OFFICE_BOY_CONTINUO_ENTREGADOR_MOTOBOY        Profession = Profession{"Office boy/Continuo/Entregador/Motoboy"}
	OFICIAL_DE_FORCAS_AUX_FORCAS_ARMADAS          Profession = Profession{"Oficial de Forças Aux e Forças Armadas"}
	OFICIAL_DE_JUSTICA                            Profession = Profession{"Oficial de Justiça"}
	OPERADOR_DE_CALDEIRA                          Profession = Profession{"Operador de Caldeira"}
	OPERADOR_DE_CAMERAS_DE_CINEMA_TV              Profession = Profession{"Operador de Cameras de Cinema e TV"}
	OPERADOR_DE_COMPUTADOR                        Profession = Profession{"Operador de Computador"}
	OPERADOR_DE_GUINDASTE                         Profession = Profession{"Operador de Guindaste"}
	OPERADOR_DE_ILUMINACAO                        Profession = Profession{"Operador de Iluminacao"}
	OPERADOR_DE_MAQUINAS_APARELHOS                Profession = Profession{"Operador de Maquinas e Aparelhos"}
	OPERADOR_DE_TELEMARKETING                     Profession = Profession{"Operador de Telemarketing"}
	OPERARIO_SEMI_ESPECIALIZADO_PRODUCAO          Profession = Profession{"Operario Semi-especializado Producao"}
	ORIENTADOR_PEDAGOGICO                         Profession = Profession{"Orientador Pedagogico"}
	OURIVES                                       Profession = Profession{"Ourives"}
	PAISAGISTA                                    Profession = Profession{"Paisagista"}
	PEDREIRO                                      Profession = Profession{"Pedreiro"}
	PENSAO_ALIMENTICIA_PARA_FILHOS                Profession = Profession{"Pensao alimenticia para filhos"}
	PENSIONISTA_                                  Profession = Profession{"Pensionista"}
	PERSONAL_TRAINER                              Profession = Profession{"Personal Trainer"}
	PESCADOR                                      Profession = Profession{"Pescador"}
	PESQUISADOR_CIENTIFICO                        Profession = Profession{"Pesquisador Cientifico"}
	PILOTO_DE_AERONAVES                           Profession = Profession{"Piloto de Aeronaves"}
	PINTOR                                        Profession = Profession{"Pintor"}
	PISCICULTOR                                   Profession = Profession{"Piscicultor"}
	PORTEIRO_ZELADOR                              Profession = Profession{"Porteiro/Zelador"}
	PORTUARIO                                     Profession = Profession{"Portuario"}
	PREFEITO                                      Profession = Profession{"Prefeito"}
	PRENSISTA_ESTAMPADOR                          Profession = Profession{"Prensista/Estampador"}
	PROCURADOR_MEMBROS_DA_PROCURADORIA            Profession = Profession{"Procurador/Membros da Procuradoria"}
	PRODUTOR_DE_EVENTOS                           Profession = Profession{"Produtor de Eventos{Promoter}/Produtor de Artes em geral"}
	PROFESSOR_AUTONOMO_PARTICULAR                 Profession = Profession{"Professor Autonomo/Particular"}
	PROFESSOR_ENSINO_FUNDAMENTAL_E_MEDIO          Profession = Profession{"Professor de Ensino Fundamental e Medio"}
	PROFESSOR_ENSINO_SUPERIOR                     Profession = Profession{"Professor de Ensino Superior"}
	PROFESSOR_IDIOMAS                             Profession = Profession{"Professor de Idiomas"}
	PROFISSIONAL_CIRCO_ACROBATA                   Profession = Profession{"Profissional de Circo/Acrobata"}
	PROFISSIONAL_LETRAS_ARTES                     Profession = Profession{"Profissional de Letras e Artes"}
	PROGRAMADOR                                   Profession = Profession{"Programador"}
	PROMOTOR_DE_VENDAS                            Profession = Profession{"Promotor de Vendas"}
	PROMOTOR_PUBLICO                              Profession = Profession{"Promotor Publico"}
	PROPRIETARIO_COMERCIAL                        Profession = Profession{"Proprietario de Estabel. Comercial"}
	PROPRIETARIO_INDUSTRIAL                       Profession = Profession{"Proprietario de Estabel. Industrial"}
	PROPRIETARIO_MICROEMPRESA                     Profession = Profession{"Proprietario de Microempresa"}
	PROPRIETARIO_PRESTACAO_SERVICOS               Profession = Profession{"Proprietario de Estabel. de Prestaçao Serviços"}
	PROPRIETARIO_RURAL_AGRICOLA_FLORESTAL_PECUARI Profession = Profession{"Proprietario de Estabel. Rural,Agricola,Florestal,Pecuario"}
	PROTETICO                                     Profession = Profession{"Protetico"}
	PSICANALISTA                                  Profession = Profession{"Psicologo/Terapeuta/Psicanalista"}
	PSICOTERAPEUTA                                Profession = Profession{"Psicologo/Terapeuta/Psicoterapeuta"}
	PUBLICITARIO                                  Profession = Profession{"Publicitario"}
	QUIMICO                                       Profession = Profession{"Quimico"}
	RADIALISTA                                    Profession = Profession{"Radialista"}
	RECEPCIONISTA                                 Profession = Profession{"Recepcionista"}
	RECICLAGEM                                    Profession = Profession{"Reciclagem - Trabalhadores em geral"}
	RECREADOR                                     Profession = Profession{"Recreador"}
	RELACOES_PUBLICAS                             Profession = Profession{"Relacoes Publicas"}
	RELOJOEIRO                                    Profession = Profession{"Relojoeiro"}
	REPRESENTANTE_COMERCIAL                       Profession = Profession{"Representante Comercial"}
	SAPATEIRO                                     Profession = Profession{"Sapateiro"}
	SECRETARIA                                    Profession = Profession{"Secretaria"}
	SECRETARIO_DE_ESTADO                          Profession = Profession{"Secretario de Estado"}
	SECRETARIO_MUNICIPAL                          Profession = Profession{"Secretario Municipal"}
	SECURITARIO                                   Profession = Profession{"Securitario"}
	SEGURANCA_PATRIMONIAL                         Profession = Profession{"Segurança Patrimonial - trabalhadores em geral"}
	SENADOR                                       Profession = Profession{"Senador"}
	SERRALHEIRO                                   Profession = Profession{"Serralheiro"}
	SERVENTUARIO_DA_JUSTICA                       Profession = Profession{"Serventuario da Justiça"}
	SERVICOS_DE_MANUTENCAO                        Profession = Profession{"Serviços de Manutencao"}
	SOCIOLOGO                                     Profession = Profession{"Sociologo"}
	SOLDADO_CORPO_DE_BOMBEIROS                    Profession = Profession{"Soldado Corpo de Bombeiros"}
	SUPERINTENDENTE                               Profession = Profession{"Superintendente"}
	SUPERVISOR                                    Profession = Profession{"Supervisor"}
	SUPERVISOR_TECNICO_OPERACIONAL                Profession = Profession{"Supervisor/Tecnico Operacional"}
	TABELIAO                                      Profession = Profession{"Tabeliao"}
	TAPECEIRO                                     Profession = Profession{"Tapeceiro"}
	TECNICO_DA_RECEITA_FEDERAL                    Profession = Profession{"Tecnico da Receita Federal"}
	TECNICO_DE_BIOLOGIA                           Profession = Profession{"Tecnico de Biologia"}
	TECNICO_DE_CONTABILIDADE                      Profession = Profession{"Tecnico de Contabilidade"}
	TECNICO_DE_ELETRICIDADE                       Profession = Profession{"Tecnico de Eletricidade"}
	TECNICO_DE_ELETRONICA                         Profession = Profession{"Tecnico de Eletronica"}
	TECNICO_DE_ESTATISTICA                        Profession = Profession{"Tecnico de Estatistica"}
	TECNICO_DE_LABORATORIO                        Profession = Profession{"Tecnico de Laboratorio"}
	TECNICO_DE_MECANICA                           Profession = Profession{"Tecnico de Mecanica"}
	TECNICO_DE_QUIMICA                            Profession = Profession{"Tecnico de Quimica"}
	TECNICO_DE_RADIOLOGIA                         Profession = Profession{"Tecnico de Radiologia"}
	TECNICO_DE_TELECOMUNICACOES                   Profession = Profession{"Tecnico de Telecomunicacoes"}
	TECNICO_EM_AGRONOMIA                          Profession = Profession{"Tecnico em Agronomia"}
	TECNICO_EM_DESPORTOS                          Profession = Profession{"Tecnico em Desportos"}
	TECNICO_EM_EDIFICACOES                        Profession = Profession{"Tecnico em Edificacoes"}
	TECNICO_EM_ELETRONICA                         Profession = Profession{"Tecnico em Eletronica"}
	TECNICO_EM_ESTATISTICA                        Profession = Profession{"Tecnico em Estatistica"}
	TECNICO_EM_FARMACIA                           Profession = Profession{"Tecnico em Farmacia"}
	TECNICO_EM_FINANCAS                           Profession = Profession{"Tecnico em Finanças"}
	TECNICO_EM_INFORMATICA                        Profession = Profession{"Tecnico em Informatica"}
	TECNICO_EM_INSEMINACAO                        Profession = Profession{"Tecnico em Inseminacao"}
	TECNICO_EM_MECANICA                           Profession = Profession{"Tecnico em Mecanica"}
	TECNICO_EM_QUIMICA                            Profession = Profession{"Tecnico em Quimica"}
	TECNICO_EM_RADIOLOGIA                         Profession = Profession{"Tecnico em Radiologia"}
	TECNICO_EM_REFRIGERACAO                       Profession = Profession{"Tecnico em Refrigeracao"}
	TECNICO_EM_TELECOMUNICACOES                   Profession = Profession{"Tecnico em Telecomunicacoes"}
	TECNICO_PROJETISTA                            Profession = Profession{"Tecnico Projetista"}
	TELEFONISTA                                   Profession = Profession{"Telefonista"}
	TERAPEUTA_OCUPACIONAL                         Profession = Profession{"Terapeuta Ocupacional"}
	TORNEIRO                                      Profession = Profession{"Torneiro"}
	TRABALHADOR_DA_ADMINISTRACAO                  Profession = Profession{"Trabalhador da Administracao"}
	TRABALHADOR_DA_PESCA                          Profession = Profession{"Trabalhador da Pesca"}
	TRABALHADOR_DE_ARTES_GRAFICASProfession                  = Profession{"Trabalhador de Artes Graficas"}
	TRABALHADOR_DE_CONSTRUCAO_CIVIL               Profession = Profession{"Trabalhador de Construcao Civil"}
	TRABALHADOR_FABRICACAO_FUMO_CIGARRO_CHARUTOS  Profession = Profession{"Trabalhador Fabricacao fumo/cigarro/charutos"}
	TRABALHADOR_FABRICACAO_FUMO_CIGARROS_CHARUTOS Profession = Profession{"Trabalhador Fabricacao fumo/cigarros/charutos"}
	TRABALHADOR_INDUSTRIAL                        Profession = Profession{"Trabalhador Industrial"}
	TRABALHADOR_RURAL                             Profession = Profession{"Trabalhador Rural"}
	TRABALHADOR_SERV_CONTABCAIXA_ASS              Profession = Profession{"Trabalhador serv. contab.caixa e ass."}
	TRAINEES                                      Profession = Profession{"Trainees"}
	VENDEDOR                                      Profession = Profession{"Vendedor"}
	VENDEDOR_PRACISTA                             Profession = Profession{"Vendedor Pracista"}
	VEREADOR                                      Profession = Profession{"Vereador"}
	VETERINARIO                                   Profession = Profession{"Veterinario"}
	VIDRACEIRO                                    Profession = Profession{"Vidraceiro"}
	WEBDESIGNER                                   Profession = Profession{"Webdesigner"}
	ZOOTECNISTA                                   Profession = Profession{"Zootecnista"}
)
