package domains

type EducationLevel string


const (
    NAO_ALFABETIZADO              EducationLevel = "NAO_ALFABETIZADO"
    ENSINO_FUNDAMENTAL_INCOMPLETO EducationLevel = "ENSINO_FUNDAMENTAL_INCOMPLETO"
    ENSINO_FUNDAMENTAL_COMPLETO   EducationLevel = "ENSINO_FUNDAMENTAL_COMPLETO"
    ENSINO_MEDIO_INCOMPLETO       EducationLevel = "ENSINO_MEDIO_INCOMPLETO"
    ENSINO_MEDIO_COMPLETO         EducationLevel = "ENSINO_MEDIO_COMPLETO"
    ENSINO_SUPERIOR_INCOMPLETO    EducationLevel = "ENSINO_SUPERIOR_INCOMPLETO"
    ENSINO_SUPERIOR_COMPLETO      EducationLevel = "ENSINO_SUPERIOR_COMPLETO"
    POS_GRADUACAO                 EducationLevel = "POS_GRADUACAO"
)
