package domains

type AccountType string

const (
	CONTA_CORRENTE_INDIVIDUAL AccountType = "CONTA_CORRENTE_INDIVIDUAL"
	CONTA_CORRENTE_CONJUNTA   AccountType = "CONTA_CORRENTE_CONJUNTA"
	CONTA_POUPANCA_CONJUNTA   AccountType = "CONTA_POUPANCA"
	CONTA_POUPANCA_INDIVIDUAL AccountType =  "CONTA_POUPANCA_INDIVIDUAL"
)
