package domains

type IdentityTypeIssuer struct {
	identityTypeIssuer string
}

const (
	SSP = IdentityTypeIssuer("SSP")
	DETRAN = IdentityTypeIssuer("DETRAN")
	CONS_REG_ECONOMIA = IdentityTypeIssuer("CONS REG ECONOMIA")
	MIN_EXERCITO = IdentityTypeIssuer("MIN EXERCITO")
	OAB = IdentityTypeIssuer("OAB")
	CREA = IdentityTypeIssuer("CREA")
	SJS = IdentityTypeIssuer("SJS")
	CTPS = IdentityTypeIssuer("CTPS")
	CREME = IdentityTypeIssuer("CREME")
	MINEX = IdentityTypeIssuer("MINEX")
	CRM = IdentityTypeIssuer("CRM")
	SJTC = IdentityTypeIssuer("SJTC")
	MAER = IdentityTypeIssuer("MAER")
	DPF = IdentityTypeIssuer("DPF")
	RBF = IdentityTypeIssuer("RBF")
	IML = IdentityTypeIssuer("IML")
	CPROF = IdentityTypeIssuer("CPROF")
	CRO = IdentityTypeIssuer("CRO")
	CRC = IdentityTypeIssuer("CRC")
	DPMAF = IdentityTypeIssuer("DPMAF")
	ME = IdentityTypeIssuer("ME")
	BM = IdentityTypeIssuer("BM")
	AERON = IdentityTypeIssuer("AERON")
	SJT = IdentityTypeIssuer("SJT")
	COREN = IdentityTypeIssuer("COREN")
	DETRA = IdentityTypeIssuer("DETRA")
	EXERC = IdentityTypeIssuer("EXERC")
	SSI = IdentityTypeIssuer("SSI")
	MINISTERIO_DA_MARINHA = IdentityTypeIssuer("MINISTERIO DA MARINHA")
	CRA_CONSELHO_ADMINISTRATIVO = IdentityTypeIssuer("CRA CONSELHO ADMINISTRATIVO")
	INSTITULO_FELIZ_PACHECO = IdentityTypeIssuer("INSTITULO FELIZ PACHECO")
	INST_NAC_PROPRIEDADE_INDUSTRIA = IdentityTypeIssuer("INST NAC PROPRIEDADE INDUSTRIA")
	MINISTERIO_DA_FAZENDA = IdentityTypeIssuer("MINISTERIO DA FAZENDA")
	TRIBUNAL_REGIONAL_DO_TRABALHO = IdentityTypeIssuer("TRIBUNAL REGIONAL DO TRABALHO")
	CONSELHO_REGIONAL_PSICOLOGIA = IdentityTypeIssuer("CONSELHO REGIONAL PSICOLOGIA")
	POLICIA_MILITAR = IdentityTypeIssuer("POLICIA MILITAR")
)