package domains

type Banks struct {
	code string
	name string
}

var (
	BANCO_DO_BRASIL              Banks  = Banks{"001", "BANCO DO BRASIL S.A."}
	BCO_DA_AMAZONIA              Banks  = Banks{"003", "BANCO DA AMAZONIA S.A."}
	BCO_DO_NORDESTE              Banks  = Banks{"004", "BANCO DO NORDESTE DO BRASIL S.A."}
	BNDES                        Banks  = Banks{"007", "BNDES"}
	CREDICOAMO                   Banks  = Banks{"010", "CREDICOAMO"}
	C_SUISSE_HEDGING             Banks  = Banks{"011", "C.SUISSE HEDGING-GRIFFO"}
	BANCO_INBURSA                Banks  = Banks{"012", "BANCO INBURSA"}
	STATE_STREET_BR              Banks  = Banks{"014", "STATE STREET BR S.A. BCO COMERCIAL"}
	UBS_BRASIL_CCTVM             Banks  = Banks{"015", "UBS BRASIL CCTVM S.A."}
	SICOOB_CREDITRAN             Banks  = Banks{"016", "SICOOB CREDITRAN"}
	BNY_MELLON                   Banks  = Banks{"017", "BNY MELLON BCO S.A."}
	BCO_TRICURY                  Banks  = Banks{"018", "BCO TRICURY S.A."}
	BCO_BANESTES                 Banks  = Banks{"021", "BCO BANESTES S.A."}
	BCO_BANDEPE                  Banks  = Banks{"024", "BCO BANDEPE S.A."}
	BCO_ALFA                     Banks  = Banks{"025", "BCO ALFA S.A."}
	BANCO_ITAÚ_CONSIGNADO        Banks  = Banks{"029", "BANCO ITAÚ CONSIGNADO S.A."}
	BANCO_SANTANDER              Banks  = Banks{"033", "BANCO SANTANDER (BRASIL) S.A."}
	BCO_BBI                      Banks  = Banks{"036", "BCO BBI S.A."}
	BCO_DO_EST_PA                Banks  = Banks{"037", "BCO DO EST. DO PA S.A."}
	BCO_CARGILL                  Banks  = Banks{"040", "BCO CARGILL S.A."}
	BCO_DO_ESTADO                Banks  = Banks{"041", "BCO DO EST. DO RS S.A."}
	BCO_DO_EST_SE                Banks  = Banks{"047", "BCO DO EST. DE SE S.A."}
	CONFIDENCE_CC                Banks  = Banks{"060", "CONFIDENCE CC LTDA."}
	HIPERCARD_BM                 Banks  = Banks{"062", "HIPERCARD BM S.A."}
	BANCO_BRADESCARD             Banks  = Banks{"063", "BANCO BRADESCARD S.A."}
	GOLDMAN_SACHS                Banks  = Banks{"064", "GOLDMAN SACHS DO BRASIL BM S.A."}
	BCO_ANDBANK                  Banks  = Banks{"065", "BCO ANDBANK S.A."}
	BCO_MORGAN_STANLEY           Banks  = Banks{"066", "BCO MORGAN STANLEY S.A."}
	BCO_CREFISA                  Banks  = Banks{"069", "BCO CREFISA S.A."}
	BRBBCO                       Banks  = Banks{"070", "BRB - BCO DE BRASILIA S.A."}
	BC__J                        Banks  = Banks{"074", "BCO RURAL MAIS S.A."}
	BCO_ABN_AMRO                 Banks  = Banks{"075", "BCO ABN AMRO S.A."}
	BCO_KDB_BRASIL               Banks  = Banks{"076", "BCO KDB BRASIL S.A."}
	BANCO_INTER                  Banks  = Banks{"077", "BANCO INTER"}
	HAITONG_BI_DO                Banks  = Banks{"078", "HAITONG BI DO BRASIL S.A."}
	BCO_ORIGINAL_DO              Banks  = Banks{"079", "BCO ORIGINAL DO AGRONEGOCIO S/A."}
	B_T_CC                       Banks  = Banks{"080", "B&T CC LTDA."}
	BANCOSEGURO_S_A              Banks  = Banks{"081", "BANCOSEGURO S.A."}
	BANCO_TOPÁZIO_S              Banks  = Banks{"082", "BANCO TOPÁZIO S.A."}
	BCO_DA_CHINA                 Banks  = Banks{"083", "BCO DA CHINA BRASIL S.A."}
	UNIPRIME_NORTE_DO            Banks  = Banks{"084", "UNIPRIME NORTE DO PARANA - CC LTDA."}
	COOP_CENTRAL_AILOS           Banks  = Banks{"085", "COOP CENTRAL AILOS"}
	CREDISAN_CC                  Banks  = Banks{"089", "CREDISAN CC"}
	CCCM_UNICRED_CENTRAL         Banks  = Banks{"091", "CCCM UNICRED CENTRAL RS"}
	BRK_S_A                      Banks  = Banks{"092", "BRK S.A. CFI"}
	POLOCRED_SCMEPP_LTDA         Banks  = Banks{"093", "POLOCRED SCMEPP LTDA"}
	BANCO_FINAXIS                Banks  = Banks{"094", "BANCO FINAXIS"}
	TRAVELEX_BANCO               Banks  = Banks{"095", "TRAVELEX BANCO DE CÂMBIO S.A."}
	BCO_B3_S                     Banks  = Banks{"096", "BCO B3 S.A."}
	CREDISIS_CENTRAL             Banks  = Banks{"097", "CREDISIS CENTRAL DE COOPERATIVAS DE CRÉDITO LTDA"}
	CREDIALIANÇA_CCR             Banks  = Banks{"098", "CREDIALIANÇA CCR LTDA."}
	UNIPRIME_CENTRAL_CCC         Banks  = Banks{"099", "UNIPRIME CENTRAL CCC LTDA."}
	PLANNER_CV_S                 Banks  = Banks{"100", "PLANNER CV S.A. CFI"}
	RENASCENCA_DTVM_LTDA         Banks  = Banks{"101", "RENASCENCA DTVM LTDA."}
	XP_INVESTIMENTOS_CCTVM       Banks  = Banks{"102", "XP INVESTIMENTOS CCTVM S.A."}
	CAIXA_ECONÔMICA_FEDERAL      Banks  = Banks{"104", "CAIXA ECONÔMICA FEDERAL"}
	LECCA_CFI_S                  Banks  = Banks{"105", "LECCA CFI S.A."}
	BCO_BOCOM_BBM                Banks  = Banks{"107", "BCO BOCOM BBM S.A."}
	PORTOCRED_S_A                Banks  = Banks{"108", "PORTOCRED S.A."}
	OLIVEIRA_TRUST_DTVM          Banks  = Banks{"111", "OLIVEIRA TRUST DTVM S.A."}
	MAGLIANO_S_A                 Banks  = Banks{"113", "MAGLIANO S.A. CCVM"}
	CENTRAL_COOPERATIVA_DE       Banks  = Banks{"114", "CENTRAL COOPERATIVA DE CRÉDITO NO ESTADO DO ESPIRITO SANTO"}
	ADVANCED_CC_LTDA             Banks  = Banks{"117", "ADVANCED CC LTDA."}
	BCO_WESTERN_UNION            Banks  = Banks{"119", "BCO WESTERN UNION"}
	BCO_RODOBENS_S               Banks  = Banks{"120", "BCO RODOBENS S.A."}
	BCO_AGIBANK_S                Banks  = Banks{"121", "BCO AGIBANK S.A."}
	BCO_BRADESCO_BERJ            Banks  = Banks{"122", "BCO BRADESCO BERJ S.A."}
	BCO_WOORI_BANK               Banks  = Banks{"124", "BCO WOORI BANK DO BRASIL S.A."}
	PLURAL_BCO_BM                Banks  = Banks{"125", "PLURAL BCO BM "}
	BR_PARTNERS_BI               Banks  = Banks{"126", "BR PARTNERS BI S.A."}
	CODEPE_CVC_S                 Banks  = Banks{"127", "CODEPE CVC S.A."}
	MS_BANK_S                    Banks  = Banks{"128", "MS BANK S.A. BCO DE CÂMBIO"}
	UBS_BRASIL_BI                Banks  = Banks{"129", "UBS BRASIL BI S.A."}
	CARUANA_SCFI                 Banks  = Banks{"130", "CARUANA S.A. CFI"}
	TULLETT_PREBON_BRASIL        Banks  = Banks{"131", "TULLETT PREBON BRASIL CVC LTDA."}
	ICBC_DO_BRASIL               Banks  = Banks{"132", "ICBC DO BRASIL BM S.A."}
	CRESOL_CONFEDERAÇÃO          Banks  = Banks{"133", "CRESOL CONFEDERAÇÃO"}
	BGC_LIQUIDEZ_DTVM            Banks  = Banks{"134", "BGC LIQUIDEZ DTVM LTDA."}
	UNICRED                      Banks  = Banks{"136", "UNICRED CENTRAL DO RIO GRANDE DO SUL"}
	GET_MONEY_CC                 Banks  = Banks{"138", "GET MONEY CC LTDA."}
	INTESA_SANPAOLO_BRASIL       Banks  = Banks{"139", "INTESA SANPAOLO BRASIL S.A. BM"}
	EASYNVEST_TÍTULO             Banks  = Banks{"140", "EASYNVEST - TÍTULO CV S.A."}
	BROKER_BRASIL_CC             Banks  = Banks{"142", "BROKER BRASIL CC LTDA."}
	TREVISO_CC_S                 Banks  = Banks{"143", "TREVISO CC S.A."}
	BEXS_BCO_DE                  Banks  = Banks{"144", "BEXS BCO DE CÂMBIO S.A."}
	LEVYCAM_CCV_LTDA             Banks  = Banks{"145", "LEVYCAM CCV LTDA."}
	GUITTA_CC_LTDA               Banks  = Banks{"146", "GUITTA CC LTDA."}
	FACTA_S_A                    Banks  = Banks{"149", "FACTA S.A. CFI"}
	ICAP_DO_BRASIL               Banks  = Banks{"157", "ICAP DO BRASIL DTVM LTDA."}
	CASA_CREDITO_S               Banks  = Banks{"159", "CASA CREDITO S.A. SCM"}
	COMMERZBANK_BRASIL_S         Banks  = Banks{"163", "COMMERZBANK BRASIL S.A. - BCO MÚLTIPLO"}
	BCO_OLÉ_BONSUCESSO           Banks  = Banks{"169", "BCO OLÉ BONSUCESSO CONSIGNADO S.A."}
	BRL_TRUST_DTVM               Banks  = Banks{"173", "BRL TRUST DTVM S.A."}
	PERNAMBUCANAS_FINANC_S       Banks  = Banks{"174", "PERNAMBUCANAS FINANC S.A. BM"}
	GUIDE                        Banks  = Banks{"177", "GUIDE"}
	CM_CAPITAL_MARKETS           Banks  = Banks{"180", "CM CAPITAL MARKETS CCTVM LTDA."}
	SOCRED_SA                    Banks  = Banks{"183", "SOCRED S.A."}
	BCO_ITAÚ_BBA                 Banks  = Banks{"184", "BCO ITAÚ BBA S.A."}
	ATIVA_S_A                    Banks  = Banks{"188", "ATIVA S.A. INVESTIMENTOS CCTVM"}
	HS_FINANCEIRA                Banks  = Banks{"189", "HS FINANCEIRA"}
	SERVICOOP                    Banks  = Banks{"190", "SERVICOOP"}
	NOVA_FUTURA_CTVM             Banks  = Banks{"191", "NOVA FUTURA CTVM LTDA."}
	PARMETAL_DTVM_LTDA           Banks  = Banks{"194", "PARMETAL DTVM LTDA."}
	FAIR_CC_S                    Banks  = Banks{"196", "FAIR CC S.A."}
	STONE_PAGAMENTOS_S           Banks  = Banks{"197", "STONE PAGAMENTOS S.A."}
	BANCO_BTG_PACTUAL            Banks  = Banks{"208", "BANCO BTG PACTUAL S.A."}
	BANCO_ORIGINAL               Banks  = Banks{"212", "BANCO ORIGINAL"}
	BCO_ARBI_S                   Banks  = Banks{"213", "BCO ARBI S.A."}
	BANCO_JOHN_DEERE             Banks  = Banks{"217", "BANCO JOHN DEERE S.A."}
	BCO_BS2_S                    Banks  = Banks{"218", "BCO BS2 S.A."}
	BCO_CRÉDIT_AGRICOLE          Banks  = Banks{"222", "BCO CRÉDIT AGRICOLE BR S.A."}
	BCO_FIBRA_S                  Banks  = Banks{"224", "BCO FIBRA S.A."}
	BANCO_CIFRA                  Banks  = Banks{"233", "BANCO CIFRA S.A."}
	BANCO_BRADESCO_S             Banks  = Banks{"237", "BANCO BRADESCO S.A."}
	BCO_CLASSICO_S               Banks  = Banks{"241", "BCO CLASSICO S.A."}
	BCO_MÁXIMA_S                 Banks  = Banks{"243", "BCO MÁXIMA S.A."}
	BCO_ABC_BRASIL               Banks  = Banks{"246", "BCO ABC BRASIL S.A."}
	BANCO_INVESTCRED_UNIBANCO    Banks  = Banks{"249", "BANCO INVESTCRED UNIBANCO S.A."}
	BCV                          Banks  = Banks{"250", "BCV"}
	BEXS_CC_S                    Banks  = Banks{"253", "BEXS CC S.A."}
	PARANA_BCO_S                 Banks  = Banks{"254", "PARANA BCO S.A."}
	MONEYCORP_BCO_DE             Banks  = Banks{"259", "MONEYCORP BCO DE CÂMBIO S.A."}
	NU_PAGAMENTOS_S              Banks  = Banks{"260", "NU PAGAMENTOS S.A."}
	BCO_FATOR_S                  Banks  = Banks{"265", "BCO FATOR S.A."}
	BCO_CEDULA_S                 Banks  = Banks{"266", "BCO CEDULA S.A."}
	BARI_CIA_HIPOTECÁRIA         Banks  = Banks{"268", "BARI CIA HIPOTECÁRIA"}
	HSBC_BANCO_DE                Banks  = Banks{"269", "HSBC BANCO DE INVESTIMENTO"}
	SAGITUR_CC_LTDA              Banks  = Banks{"270", "SAGITUR CC LTDA."}
	IB_CCTVM_S                   Banks  = Banks{"271", "IB CCTVM S.A."}
	AGK_CC_S                     Banks  = Banks{"272", "AGK CC S.A."}
	CCR_DE_SÃO                   Banks  = Banks{"273", "CCR DE SÃO MIGUEL DO OESTE"}
	MONEY_PLUS_SCMEPP            Banks  = Banks{"274", "MONEY PLUS SCMEPP LTDA."}
	SENFF_S_A                    Banks  = Banks{"276", "SENFF S.A. - CFI."}
	GENIAL_INVESTIMENTOS_CVM     Banks  = Banks{"278", "GENIAL INVESTIMENTOS CVM S.A."}
	CCR_DE_PRIMAVERA             Banks  = Banks{"279", "CCR DE PRIMAVERA DO LESTE"}
	AVISTA_S_A                   Banks  = Banks{"280", "AVISTA S.A. CFI"}
	CCR_COOPAVEL                 Banks  = Banks{"281", "CCR COOPAVEL"}
	RB_CAPITAL_INVESTIMENTOS     Banks  = Banks{"283", "RB CAPITAL INVESTIMENTOS DTVM LTDA."}
	FRENTE_CC_LTDA               Banks  = Banks{"285", "FRENTE CC LTDA."}
	CCR_DE_OURO                  Banks  = Banks{"286", "CCR DE OURO PRETO"}
	CAROL_DTVM_LTDA              Banks  = Banks{"288", "CAROL DTVM LTDA."}
	DECYSEO_CC_LTDA              Banks  = Banks{"289", "DECYSEO CC LTDA."}
	PAGSEGURO                    Banks  = Banks{"290", "PAGSEGURO"}
	BS2_DTVM_S                   Banks  = Banks{"292", "BS2 DTVM S.A."}
	LASTRO_RDV_DTVM              Banks  = Banks{"293", "LASTRO RDV DTVM LTDA."}
	VISION_S_A                   Banks  = Banks{"296", "VISION S.A. CFI"}
	VIPS_CC_LTDA                 Banks  = Banks{"298", "VIPS CC LTDA."}
	SOROCRED_CFI_S               Banks  = Banks{"299", "SOROCRED CFI S.A."}
	BCO_LA_NACION                Banks  = Banks{"300", "BCO LA NACION ARGENTINA"}
	BPP_IP_S                     Banks  = Banks{"301", "BPP IP S.A."}
	PORTOPAR_DTVM_LTDA           Banks  = Banks{"306", "PORTOPAR DTVM LTDA."}
	TERRA_INVESTIMENTOS_DTVM     Banks  = Banks{"307", "TERRA INVESTIMENTOS DTVM"}
	CAMBIONET_CC_LTDA            Banks  = Banks{"309", "CAMBIONET CC LTDA."}
	VORTX_DTVM_LTDA              Banks  = Banks{"310", "VORTX DTVM LTDA."}
	PI_DTVM_S                    Banks  = Banks{"315", "PI DTVM S.A."}
	BCO_BMG_S                    Banks  = Banks{"318", "BCO BMG S.A."}
	OM_DTVM_LTDA                 Banks  = Banks{"319", "OM DTVM LTDA."}
	BCO_CCB_BRASIL               Banks  = Banks{"320", "BCO CCB BRASIL S.A."}
	CREFAZ_SCMEPP_LTDA           Banks  = Banks{"321", "CREFAZ SCMEPP LTDA."}
	CCR_DE_ABELARDO              Banks  = Banks{"322", "CCR DE ABELARDO LUZ"}
	MERCADO_PAGO                 Banks  = Banks{"323", "MERCADO PAGO"}
	ÓRAMA_DTVM_S                 Banks  = Banks{"325", "ÓRAMA DTVM S.A."}
	PARATI_CFI                   Banks  = Banks{"326", "PARATI CFI S.A."}
	QI_SCD_S                     Banks  = Banks{"329", "QI SCD S.A."}
	BANCO_BARI_S                 Banks  = Banks{"330", "BANCO BARI S.A."}
	FRAM_CAPITAL_DTVM            Banks  = Banks{"331", "FRAM CAPITAL DTVM S.A."}
	ACESSO                       Banks  = Banks{"332", "ACESSO"}
	BANCO_DIGIO                  Banks  = Banks{"335", "BANCO DIGIO"}
	BCO_C6_S                     Banks  = Banks{"336", "BCO C6 S.A."}
	SUPER_PAGAMENTOS_E           Banks  = Banks{"340", "SUPER PAGAMENTOS E ADMINISTRAÇÃO DE MEIOS ELETRÔNICOS S.A."}
	ITAÚ_UNIBANCO_S              Banks  = Banks{"341", "ITAÚ UNIBANCO S.A."}
	CREDITAS_SCD                 Banks  = Banks{"342", "CREDITAS SCD S.A."}
	FFA_SCMEPP_LTDA              Banks  = Banks{"343", "FFA SCMEPP LTDA."}
	BCO_XP_S                     Banks  = Banks{"348", "BCO XP S.A."}
	AMAGGI_S_A                   Banks  = Banks{"349", "AMAGGI S.A. CFI"}
	TORO_CTVM_LTDA               Banks  = Banks{"352", "TORO CTVM LTDA."}
	NECTON_INVESTIMENTOS_S       Banks  = Banks{"354", "NECTON INVESTIMENTOS S.A."}
	ÓTIMO_SCD_S                  Banks  = Banks{"355", "ÓTIMO SCD S.A."}
	GERENCIANET_PAGTOS_BRASIL    Banks  = Banks{"364", "GERENCIANET PAGTOS BRASIL S.A."}
	SOLIDUS_S_A                  Banks  = Banks{"365", "SOLIDUS S.A. CFI"}
	BCO_SOCIETE_GENERALE         Banks  = Banks{"366", "BCO SOCIETE GENERALE BRASIL S.A."}
	VITREO_DTVM_S                Banks  = Banks{"367", "VITREO DTVM S.A."}
	BCO_MIZUHO_S                 Banks  = Banks{"370", "BCO MIZUHO S.A."}
	UP_P_SEP                     Banks  = Banks{"373", "UP.P SEP S.A."}
	BCO_J_P                      Banks  = Banks{"376", "BCO J.P. MORGAN S.A."}
	BCO_MERCANTIL_DO             Banks  = Banks{"389", "BCO MERCANTIL DO BRASIL S.A."}
	BCO_BRADESCO_FINANC          Banks  = Banks{"394", "BCO BRADESCO FINANC S.A."}
	KIRTON_BANK                  Banks  = Banks{"399", "KIRTON BANK"}
	BCO_CAPITAL_S                Banks  = Banks{"412", "BCO CAPITAL S.A."}
	BCO_BV_S                     Banks  = Banks{"413", "BCO BV S.A."}
	BCO_SAFRA_S                  Banks  = Banks{"422", "BCO SAFRA S.A."}
	FITBANK_PAGAMENTOS_ELETRONICOBanksS = Banks{"450", "FITBANK PAGAMENTOS ELETRÔNICOS S.A."}
	BCO_MUFG_BRASIL              Banks  = Banks{"456", "BCO MUFG BRASIL S.A."}
	BCO_SUMITOMO_MITSUI          Banks  = Banks{"464", "BCO SUMITOMO MITSUI BRASIL S.A."}
	BCO_CAIXA_GERAL              Banks  = Banks{"473", "BCO CAIXA GERAL BRASIL S.A."}
	CITIBANK_N_A                 Banks  = Banks{"477", "CITIBANK N.A."}
	BCO_ITAUBANK_S               Banks  = Banks{"479", "ITAUBANK S.A."}
	DEUTSCHE_BANK_S              Banks  = Banks{"487", "DEUTSCHE BANK S.A. BCO ALEMAO"}
	JPMORGAN_CHASE_BANK          Banks  = Banks{"488", "JPMORGAN CHASE BANK"}
	ING_BANK_N                   Banks  = Banks{"492", "ING BANK N.V."}
	BCO_LA_PROVINCIA             Banks  = Banks{"495", "BCO LA PROVINCIA B AIRES BCE"}
	BCO_CREDIT_SUISSE            Banks  = Banks{"505", "BCO CREDIT SUISSE S.A."}
	SENSO_CCVM_S                 Banks  = Banks{"545", "SENSO CCVM S.A."}
	BCO_LUSO_BRASILEIRO          Banks  = Banks{"600", "BCO LUSO BRASILEIRO S.A."}
	BCO_INDUSTRIAL_DO            Banks  = Banks{"604", "BCO INDUSTRIAL DO BRASIL S.A."}
	BCO_VR_S                     Banks  = Banks{"610", "BCO VR S.A."}
	BCO_PAULISTA_S               Banks  = Banks{"611", "BCO PAULISTA S.A."}
	BCO_GUANABARA_S              Banks  = Banks{"612", "BCO GUANABARA S.A."}
	OMNI_BANCO_S                 Banks  = Banks{"613", "OMNI BANCO S.A."}
	BANCO_PAN                    Banks  = Banks{"623", "BANCO PAN"}
	BCO_FICSA_S                  Banks  = Banks{"626", "BCO FICSA S.A."}
	SMARTBANK                    Banks  = Banks{"630", "SMARTBANK"}
	BCO_RENDIMENTO_S             Banks  = Banks{"633", "BCO RENDIMENTO"}
	BCO_TRIANGULO_S              Banks  = Banks{"634", "BCO TRIANGULO S.A."}
	BCO_SOFISA_S                 Banks  = Banks{"637", "BCO SOFISA S.A."}
	BCO_PINE_S                   Banks  = Banks{"643", "BCO PINE S.A."}
	ITAÚ_UNIBANCO_HOLDING        Banks  = Banks{"652", "ITAÚ UNIBANCO HOLDING S.A."}
	BCO_INDUSVAL_S               Banks  = Banks{"653", "BCO INDUSVAL S.A."}
	BCO_A_J                      Banks  = Banks{"654", "BCO A.J. RENNER S.A."}
	BCO_DAYCOVAL_S               Banks  = Banks{"707", "BCO DAYCOVAL S.A."}
	BCO_OURINVEST_S              Banks  = Banks{"712", "BCO OURINVEST S.A."}
	BANCO_NEON                   Banks  = Banks{"735", "BANCO NEON"}
	BCO_CETELEM_S                Banks  = Banks{"739", "BCO CETELEM S.A."}
	BCO_RIBEIRAO_PRETO           Banks  = Banks{"741", "BCO RIBEIRAO PRETO S.A."}
	BANCO_SEMEAR                 Banks  = Banks{"743", "BANCO SEMEAR"}
	BCO_CITIBANK_S               Banks  = Banks{"745", "BCO CITIBANK S.A."}
	BCO_MODAL_S                  Banks  = Banks{"746", "BCO MODAL S.A."}
	BCO_RABOBANK_INTL            Banks  = Banks{"747", "BCO RABOBANK INTL BRASIL S.A."}
	BCO_COOPERATIVO_SICREDI      Banks  = Banks{"748", "BCO COOPERATIVO SICREDI S.A."}
	SCOTIABANK_BRASIL            Banks  = Banks{"751", "SCOTIABANK BRASIL"}
	BCO_BNP_PARIBAS              Banks  = Banks{"752", "BCO BNP PARIBAS BRASIL S.A."}
	NOVO_BCO_CONTINENTAL         Banks  = Banks{"753", "NOVO BCO CONTINENTAL S.A. - BM"}
	BANCO_SISTEMA                Banks  = Banks{"754", "BANCO SISTEMA"}
	BOFA_MERRILL_LYNCH           Banks  = Banks{"755", "BOFA MERRILL LYNCH BM S.A."}
	BANCOOB                      Banks  = Banks{"756", "BANCOOB"}
	BCO_KEB_HANA                 Banks  = Banks{"757", "BCO KEB HANA DO BRASIL S.A."}
	CLARO_PAY_S                  Banks  = Banks{"759", "CLARO PAY S.A."}
)
