name: Go package

on:
    push:
        branches:
          - features/TR-6298
        tags:
          - v\d+.\d+.\d+.*
          - v\d+.\d+.*
          - v\d+.*
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.2

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...