name: Deploy on tag

on:
  push:
      tags:
         - v\d+.\d+.\d+.*

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3

        with:
          go-version: 1.19.2
          registry-url: https://pkg.go.dev/
          scope: '@Fitbank-Pagamentos-Eletronicos'

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...